# -*- coding: utf-8 -*-
"""
Automatically generated by DeachSword-DearSakura
Author: YinMo (WEDeach)
Version: 1.0.5
"""


from ..helper import ChrHelperProtocol
from .BaseService import BaseServiceSender


class InterlockService(ChrHelperProtocol):
    __REQ_TYPE = 4
    __RES_TYPE = 4
    __ENDPOINT = "/EIS4"

    def __init__(self):
        self.__sender = BaseServiceSender(
            self.client,
            __class__.__name__,
            self.__REQ_TYPE,
            self.__RES_TYPE,
            self.__ENDPOINT,
        )

    def getPlaceSearchProviderList(self, region: str):
        """
        Get place search provider list.

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 02/03/2023, 23:02:07
        """
        METHOD_NAME = "getPlaceSearchProviderList"
        params = [[11, 1, region]]
        return self.__sender.send(METHOD_NAME, params)

    def getPlaceSearchInfo(
        self,
        provider: int,
        keyword: str,
        clientLocale: str,
        latitude: float,
        longitude: float,
        radius: int,
    ):
        """
        Get place search info.

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 02/03/2023, 23:02:07
        """
        METHOD_NAME = "getPlaceSearchInfo"
        params = [
            [8, 2, provider],  # 0
            [11, 3, keyword],  # 台北101
            [11, 4, clientLocale],
            [4, 5, latitude],  # 25.03303
            [4, 6, longitude],  # 121.562759
            [8, 7, radius],
        ]
        return self.__sender.send(METHOD_NAME, params)
