# -*- coding: utf-8 -*-

from ..helper import ChrHelperProtocol
from .BaseService import BaseServiceSender, BaseServiceStruct


class LoginService(ChrHelperProtocol):
    __REQ_TYPE = 4
    __RES_TYPE = 4
    __ENDPOINT = "/acct/lgn/sq/v1"

    def __init__(self):
        self.__sender = BaseServiceSender(
            self.client,
            "SecondaryQrCodeLoginService",
            self.__REQ_TYPE,
            self.__RES_TYPE,
            self.__ENDPOINT,
        )

    def qrCodeLoginForSecure(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 10/31/2022, 08:17:56
        """
        raise Exception("qrCodeLoginForSecure is not implemented")
        METHOD_NAME = "qrCodeLoginForSecure"
        params = []
        return self.__sender.send(METHOD_NAME, params)

    def qrCodeLoginV2ForSecure(
        self,
        authSessionId: str,
        modelName: str,
        systemName: str,
        secureCode: str,
        autoLoginIsRequired: bool = True,
    ):
        """
        Qr code login v2 for secure.

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 10/31/2022, 08:17:56
        """
        METHOD_NAME = "qrCodeLoginV2ForSecure"
        params = [
            [11, 1, authSessionId],
            [11, 2, systemName],
            [11, 3, modelName],
            [2, 4, autoLoginIsRequired],
            [11, 5, secureCode],
        ]
        params = BaseServiceStruct.BaseRequest(params)
        return self.__sender.send(METHOD_NAME, params)

    def createQrCodeForSecure(self, qrcode: str):
        """
        Create qr code for secure.

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.5.py
        DATETIME: 10/31/2022, 08:17:56
        """
        METHOD_NAME = "createQrCodeForSecure"
        params = [[11, 1, qrcode]]
        params = BaseServiceStruct.BaseRequest(params)
        return self.__sender.send(METHOD_NAME, params)
