# -*- coding: utf-8 -*-
"""
Automatically generated by DeachSword-DearSakura
Author: YinMo (WEDeach)
Version: 1.0.6
"""

from typing import List, Optional

from ..helper import ChrHelperProtocol
from .BaseService import BaseServiceSender


class RelationService(ChrHelperProtocol):
    __REQ_TYPE = 4
    __RES_TYPE = 4
    __ENDPOINT = "/RE4"

    def __init__(self):
        self.__sender = BaseServiceSender(
            self.client,
            "RelationService",
            self.__REQ_TYPE,
            self.__RES_TYPE,
            self.__ENDPOINT,
        )

    def getTargetProfiles(self, mids: List[str]):
        """
        Get target profiles (test).

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        METHOD_NAME = "getTargetProfiles"
        targets = []
        for mid in mids:
            targets.append([[11, 1, mid]])
        request = [[15, 1, [12, targets]]]
        params = [[12, 1, request]]
        return self.__sender.send(METHOD_NAME, params)

    def getUserStatuses(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getUserStatuses is not implemented")
        METHOD_NAME = "getUserStatuses"
        params = []
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def getRecommendationDetails(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getRecommendationDetails is not implemented")
        METHOD_NAME = "getRecommendationDetails"
        params = []
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def getContactCalendarEvents(
        self,
        targetUserMids: List[str],
        syncReason: int,
        requiredContactCalendarEvents: List[int],
    ):
        """Get contact calendar events"""
        METHOD_NAME = "getContactCalendarEvents"
        __last_updated = "2024/05/09"
        targetUsers = []
        for mid in targetUserMids:
            targetUsers.append([[11, 1, mid, "targetUserMid"]])
        params = [
            [15, 1, [12, targetUsers]],
            [8, 2, syncReason],
            [14, 3, [8, requiredContactCalendarEvents]],
        ]
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def getBlockDetails(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getBlockDetails is not implemented")
        METHOD_NAME = "getBlockDetails"
        params = []
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def getContactsV3(
        self,
        targetUserMids: List[str],
        syncReason: int = 5,
        checkUserStatusStrictly: bool = False,
    ):
        """Get contacts v3."""
        METHOD_NAME = "getContactsV3"
        __last_updated = "2024/05/09"
        targetUsers = []
        for mid in targetUserMids:
            targetUsers.append([[11, 1, mid, "targetUserMid"]])
        params = [
            [15, 1, [12, targetUsers]],
            [8, 2, syncReason],
            [2, 3, checkUserStatusStrictly],
        ]
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def getFriendDetails(self):
        """
        AUTO_GENERATED_CODE! DONT_USE_THIS_FUNC!!

        GENERATED BY YinMo0913_DeachSword-DearSakura_v1.0.6.py
        DATETIME: 03/10/2023, 13:41:11
        """
        raise Exception("getFriendDetails is not implemented")
        METHOD_NAME = "getFriendDetails"
        params = []
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def addFriendByMid(
        self,
        userMid: str,
        reference: str = '{"spec":"native","screen":"talkroom:message"}',
        trackingMetaType: int = 5,
        trackingMetaHint: Optional[str] = None,
    ):
        """Add friend by mid."""
        METHOD_NAME = "addFriendByMid"
        addMeta = [[11, 1, trackingMetaHint]]
        trackingMeta = [[12, trackingMetaType, addMeta]]
        tracking = [[11, 1, reference], [12, 2, trackingMeta]]
        params = [
            [8, 1, self.client.getCurrReqId()],
            [11, 2, userMid],
            [12, 3, tracking],
        ]
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)

    def getTargetProfileNotice(self, targetUserMid: str):
        """Get target profile notice."""
        METHOD_NAME = "getTargetProfileNotice"
        params = [
            [11, 1, targetUserMid],
        ]
        params = [[12, 1, params]]
        return self.__sender.send(METHOD_NAME, params)
